# Base configs
baseurl: "aztejeda.me"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "UA-46465113-2"

# UI configs
title: "Photography by Adam Tejeda"
subtitle: ""
author: "Adam Tejeda"
header:
 title: "Photography"
 subtitle: "by Adam Tejeda"
footer:
 name: "Hey there, my name is Adam"
 bio: ""
 github: ""
web_design: "AJ"
social_urls:
  instagram: "https://www.instagram.com/aztejeda"
